class_name NetConfig

const INITIAL_INTERP_DELAY_TICKS := 6.0

const INTERP_DELAY_MARGIN_TICKS := 2.0
const MIN_INTERP_DELAY_TICKS := 2.0
const MAX_INTERP_DELAY_TICKS := 20.0

const DELAY_GROW_RATE := 0.5
const DELAY_SHRINK_RATE := 0.03

const PING_INTERVAL := 0.5
const PING_SMOOTHING := 0.2
const PING_SPIKE_SMOOTHING := 0.5
const PING_DECAY_SMOOTHING := 0.03

const SNAPSHOT_HISTORY := 32

const PLAYHEAD_CORRECTION := 0.1

const PLAYHEAD_RESYNC_TICKS := 10.0

const IP_ADDRESS := "127.0.0.1"
const PORT := 4242
const MAX_CLIENTS := 4